version: '2'

services:
 influxdb:
  image: tutum/influxdb
  container_name: influxdb
  environment:
   - PRE_CREATE_DB="toptal"
  ports:
   - '8083:8083'
   - '8086:8086'
   - '8090:8090'
  volumes:
   - graphana_storage:/var/lib/grafana

 grafana:
  image: grafana/grafana
  container_name: grafana
  ports:
   - '3000:3000'

volumes:
  graphana_storage:
